global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  receiver: "slack-notifications"

receivers:
- name: "slack-notifications"
  slack_configs:
  - channel: "#igor_shokhov"
